airlineSim:
	g++ -std=c++11 -o airlineSim -I ../inc/ ECConsoleUITextLabel.cpp ECTextViewImp.cpp ECConsoleUIView.cpp ECConsoleUIListBox.cpp ECConsoleUITextField.cpp ECConsoleUIButton.cpp ECConsoleFlightButton.cpp ECAirlineOperation.cpp ECAirlineSimulator.cpp ECAirport.cpp ECFlight.cpp ECFlightItinerary.cpp CompleteTest.cpp

test:
	clang++ -g -std=c++11 -o test -I ../inc/ ECConsoleUITextLabel.cpp ECTextViewImp.cpp ECConsoleUIView.cpp ECConsoleUIListBox.cpp ECConsoleUITextField.cpp ECConsoleUIButton.cpp ECConsoleFlightButton.cpp ECAirlineOperation.cpp ECAirlineSimulator.cpp ECAirport.cpp ECFlight.cpp ECFlightItinerary.cpp CompleteTest.cpp

clean:
	rm -rf airlineSim  test test.dSYM
